# Generated by Django 5.0.10 on 2025-01-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
